name: Duplicate Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run duplicate check
        run: |
          python check_duplicates.py
